// <auto-generated />
namespace SerialPortApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class localdb_init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(localdb_init));
        
        string IMigrationMetadata.Id
        {
            get { return "202101132310351_localdb_init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
